---
title: Neural Networks for FCing
author: Ross
date: '2017-06-25'
slug: neural-networks-for-fcing
categories:
  - R
  - Forecast
tags: []
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
invisible(library(forecast))
invisible(library(TStools))
library(forecast)
library(MAPA)
library(TStools)

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
setwd("/Users/rosseji/Dropbox/TrendLock/ISF/forecasting with R/")
# Load the three time series, as before
ts1 <- ts(scan("ts1.txt"), start=c(2011,1), frequency=4)
ts2 <- ts(scan("ts2.txt"), start=c(2011,1), frequency=12)
# In order to evaluate our forecasts let us load some test data as well. 
ts1.test <- ts(scan("ts1out.txt"), start=c(2016,1), frequency=4)
ts2.test <- ts(scan("ts2out.txt"), start=c(2016,1), frequency=12)

# Let us first model ts2
y <- ts2
y.test <- ts2.test

# Let us store the time series to be explored in variable `y' so that we can  
# repeat the analysis easily with new data if needed.
y <- ts2
```

Woh, didn't think we'd put putting this into practive so soon!

```{r}

#neural networks
fit.nnetar <- nnetar(ts2)
print(fit.nnetar)
frc.nnetar <- forecast(fit.nnetar, h = 12)
plot(frc.nnetar)
```